---
version: 4.0.0
title: Extremum Schema Repository
logo: "http://extremum.io/images/extremum-logo-800x800.png"
description: Extensible data schemas for better web services
url: http://schema.extremum.io
repository: https://github.com/extremum-community/extremum-schema
timezone: UTC
google_analytics_id: UA-165727637-2
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
exclude:
- CNAME
theme: jekyll-theme-hacker
